### ISSUE TITLE
Feature Request: preserve individual failures of the resolvers

### ISSUE THREAD

**Issue by neurasium** [OxfordAbstracts/purescript-graphql-client#111]
Complex pages require complex, deeply nested queries, and in such cases chances that _something_ will fail along the way can be difficult to bound to zero. At certain times an *insignificant* piece of data fails to load, so throwing an error for the whole query would lead to a bad user experience. An option to mitigate this is to give the user of `purescript-graphql-client` power to decide what to do with such failures. Luckily, GraphQL already adorns the returned responses with an error list, each element of which point at a resolver that failed. Thus the library could have returned a response to the user which would have `Either Error` wrapping **every** returned subfield in the deeply nested object.

E.g. today a query  ` user: id =>> { name }` returns type of `{ user :: { name :: String } }`, but it could return `{ user :: Either Error { name :: Either Error String } }`. 

If the library also provides a function  to traverse the fields of such a structure and attempt to reconstruct the value of the type that the library returns currently, the user experience is improved. They get the original behavior if use it at the root level, but if things should be allowed to fail separately, they can still use this function on some substructure of the returned object.

**Comment by roryc89** [comment]
@neurasium I think this is a good idea and can definitely see the the use of this. 

I think it may have to return `Either (Maybe Error) a` instead of `Either Error a` in case the graphql server doesn't respond with an error at the correct path. 

I'll look into implementing this, or something like it, in the next few weeks.

**Comment by roryc89** [comment]
I will probably add a function to get the raw json response with data and errors with a phantom response type and then some utilities for performing this type of conversion.

**Comment by bakhtiyarneyman** [comment]
Exciting!

A couple data points which are _very_ tangentially relevant. I'm only bringing them up because it seems like a significant user-facing API expansion might be coming, and it has to do with reporting errors.

1) Our backend is using 401 code when auth failed for any reason. The frontend must react to this by logging out the user. Thus we need to inspect the __network error__ reported by the base graphql client (urql in our case). 
2) in 95%> of our graphql calls we are calling into a _single_ resolver at the root level. 
3) Often times types returned from the endpoint need slight modification.

To accommodate this, we wrote a small module which attempts to improve the standard API provided by the library. Sharing what we have because it might be useful to inspire changes in the library itself.

https://gist.github.com/bakhtiyarneyman/a53e44f3c00f2754845f42dcdb3d87f4

**Comment by roryc89** [comment]
Thanks! Having an graphql error type definitely makes sense. I'll have a closer look when I add the error boundaries/handling

**Comment by roryc89** [comment]
@neurasium In branch https://github.com/OxfordAbstracts/purescript-graphql-client/tree/keep-errors-%23111 I've added `ErrorBoundary`s that allow you to prevent errors from bubbling up the decoders. `putErrorsInPaths` then adds the errors at their correct paths. `examples/13-error-boundaries` demos these steps. 

Let me know if this works in your project. 

@bakhtiyarneyman I've also added functions to return the json responses with phantom types. You should see them in https://github.com/OxfordAbstracts/purescript-graphql-client/pull/116

**Comment by bakhtiyarneyman** [comment]
Great stuff, Rory! From a superficial look at it, it's just what we need. I'll evaluate and report back in a few weeks.

**Comment by roryc89** [comment]
that's great - thanks!

**Comment by bakhtiyarneyman** [comment]
Sorry for the long delay, finally ready to report back.

I think it's a perfect unintrusive design! All my attempts to improve it circled back to what you had. The only few comments that  I have are 
1) [This one here](https://www.github.com/OxfordAbstracts/purescript-graphql-client/commit/79c824cec365847e7de361899d6b375bf799c8f4#r117551303)
2) We opted to keep our own decoding of Urql-specific JSON and map the errors to approximately the following data type, which results in less cryptic errors when the server is not spec-compliant.

```
data Error
  = MalformedResponse
      { responseDecodeError :: JsonDecodeError
      , responseJson :: Json
      }
  | NetworkError String
  | MalformedData
      { gqlErrors :: NE.NonEmptyArray GqlError
      , dataDecodeError :: JsonDecodeError
      , response :: Response
      }
  | MalformedGqlErrors
      { gqlDecodeError :: JsonDecodeError
      , response :: Response
      }
  | MissingGqlErrors
      { dataDecodeError :: JsonDecodeError
      , response :: Response
      }

```
